### ISSUE TITLE
Cmake error at conan_support.cmake

### ISSUE THREAD

**Issue by Zaenalos** [ZTzTopia/GTProxy#73]
Error occurs when building in Termux.

Error:

CMake Error at vendor/cmake-conan/conan_support.cmake:147 (message):
  Conan install failed='6'
Call Stack (most recent call first):
  vendor/cmake-conan/conan_support.cmake:175 (conan_install)
  src/CMakeLists.txt:52 (find_package)

![Screenshot_2023-09-01-13-56-40-973_com.termux.png](https://github.com/ZTzTopia/GTProxy/assets/77824453/f0eafb4e-c9e4-4c3f-ab7e-00d0561eba0f)

**Comment by ZTzTopia** [comment]
Looks like cmake-conan isn't quite finished yet, but i don't know about cmake-conan at the moment because i haven't updated the submodule of cmake-conan.

**Comment by Zaenalos** [comment]
> Looks like cmake-conan isn't quite finished yet, but i don't know about cmake-conan at the moment because i haven't updated the submodule of cmake-conan.

Thanks for the reply, i'll try to fix it and commit a push if fixed.

**Comment by Zaenalos** [comment]
Just got fixed the first problem which is the arguments  of conan install.


Second problem:

 ```
ERROR: Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/conan/cli/cli.py", line 272, in main
    cli.run(args)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/conan/cli/cli.py", line 172, in run
    command.run(self._conan_api, args[0][1:])
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/conan/cli/command.py", line 125, in run
    info = self._method(conan_api, parser, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/conan/cli/commands/install.py", line 62, in install
    profile_host, profile_build = conan_api.profiles.get_profiles_from_args(args)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/conan/api/subapi/profiles.py", line 36, in get_profiles_from_args
    profile_host = self.get_profile(profiles=host, settings=args.settings_host,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/conan/api/subapi/profiles.py", line 48, in get_profile
    profile = loader.from_cli_args(profiles, settings, options, conf, cwd)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/conans/client/profile_loader.py", line 135, in from_cli_args
    args_profile = _profile_parse_args(settings, options, conf)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/conans/client/profile_loader.py", line 395, in _profile_parse_args
    result.options = Options.loads("\n".join(options or []))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/conans/model/options.py", line 268, in loads
    name, value = line.split("=", 1)
    ^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

ERROR: not enough values to unpack (expected 2, got 1)
```

![Screenshot_2023-09-01-15-38-13-864_com.termux.png](https://github.com/ZTzTopia/GTProxy/assets/77824453/69d0c013-c965-4644-a247-5dc1124c5cdc)

**Comment by eikarna** [comment]
Any update?
